runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: django
  version: 1.4
- name: ssl
  version: latest

handlers:
- url: /css
  static_dir: static/css
  
- url: /img
  static_dir: static/img
  
- url: /js
  static_dir: static/js
  
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /contact.html
  static_files: static/contact.html
  upload: static/contact.html
  
- url: /viewport
  static_files: static/viewport.html
  upload: static/viewport.html
  
- url: /fables
  static_dir: static/fables
  
- url: /admin/.*
  script: fableme.admin.ADMIN_APP
  login: admin
  
- url: /.*
  script: main.APPLICATION

builtins:
- deferred: on



